### ISSUE TITLE
Images of nuclei acid staining Missing

### ISSUE THREAD

**Issue by Tailion9** [STOmics/SAW#137]
Thanks for the valuable dataset!
As I tried to find all the images for MOSTA on : 
[MOSTA](https://db.cngb.org/stomics/mosta/download/)
I found only 6 tif image files. 
I wonder if there's been a mistake and whether other images are public unavailable, as I hope to download all the images.
Thank you !

**Comment by Jinghao-Chen** [comment]
Hi, thank you for your interest. We‘re sorry that we are not directly involved in the work of the MOSTA. You could try to contact the administrator of MOSTA or the submitter. In addition, because the tiff images on MOSTA were used for cell segmentation and expression matrix extraction(GEM_CellBin.tsv.gz), the images correspond to the CellBin expression matrix.

**Comment by Tailion9** [comment]
All right. Thanks for you time!
