### ISSUE TITLE
E13.5 "trim" fastq files: read length are not the same in the fastq file

### ISSUE THREAD

**Issue by Ed2uiz** [STOmics/SAW#16]
Hello,

I'm encountering the following error when running E13.5 samples downloaded from the CNGB website which have the word "trim" in the filename (e.g. E13.5_E1S1, CNR0431569, "DP8400015451TL_L01_read_trim_2.fq.gz", "trim_DP8400015451TL_L01_read_trim_1.fq.gz"). 

Are there specific processing steps that need to be performed on these fastq files to be able to use them in the SAW pipeline? 

Thanks,
Ed

```
 ~~~ pre-mapping CIDcount ~~~
parse:[MEM]max:703700, avg:0; [CPU]real:61.78, user:43.39.sys:4.85, cpu:78%; [IO]i14657354, o:16
 ~~~ mapping - trim_DP8400018317BL_L01_read_trim_1.fq.gz} ~~~
--runThreadN 8
WARNING: While bind mounting '/projectnb/rd-spat/HOME/ecruiz/StereoSeq/raw_data/E13.5_E1S1:/projectnb/rd-spat/HOME/ecruiz/StereoSeq/raw_data/E13.5_E1S1': destination is already in the mount point list
WARNING: While bind mounting '/projectnb/rd-spat/HOME/ecruiz/StereoSeq/raw_data/E13.5_E1S1:/projectnb/rd-spat/HOME/ecruiz/StereoSeq/raw_data/E13.5_E1S1': destination is already in the mount point list
read length are not the same in the fastq file, @DP8400018317BLL1C001R00400000036 166620F16A075 C2DA3
ATCCGACTTAGTGTGCGAAGTCGGAGGAGAGATATTCCTGGAAATTGCGG
+
AIFG2FGHHHBFAEGGIGH;FFICGFDF97EGFHHDFHGEDHHIFGHGE>
```

**Comment by Clouate** [comment]
@Ed2uiz Hello, this error is due to different length of the reads in your DP8400015451TL_L01_read_trim_2.fq.gz. There may be errors with the data itself, I think.
![1662723643(1)](https://user-images.githubusercontent.com/58293762/189342163-196aa653-7b87-4eee-a10d-390ff69da24b.png)

For example, length of the read in your error message(length=50) is different from others(length=100):

**@DP8400018317BLL1C001R00400000036 166620F16A075 C2DA3
ATCCGACTTAGTGTGCGAAGTCGGAGGAGAGATATTCCTGGAAATTGCGG
+
AIFG2FGHHHBFAEGGIGH;FFICGFDF97EGFHHDFHGEDHHIFGHGE>**

If you just want to run SAW for a test, you may download the test data in our SAW repository.

Best wishes!

**Comment by Ed2uiz** [comment]
Hello @Clouate,

Thank you for the prompt reply. I am interested in running any one of the four sections of the E13.5 samples. It appears that all sections for E13.5 have the "trim" fastq files. Are all of these 'trim' fastq files corrupted? If not, can you please advise how to process these "trim" fastq files so that they work with the SAW pipeline?

**Comment by Clouate** [comment]
@Ed2uiz 
Sorry, I check the content of the two fastq files(DP8400015451TL_L01_read_trim_2.fq.gz" & "trim_DP8400015451TL_L01_read_trim_1.fq.gz) and found that they do not work with SAW pipeline either our internal analysis pipeline present.
SAW would check if read length are the same or not before running barcodeMapping, you may edit the fastq files (delete the correspoding short reads in 1.fq.gz and 2.fq.gz) so that they work with the SAW pipeline. But it may affect the analysis results. 
I would recommend contacting the submitter in the CNGB website(https://db.cngb.org/search/sample/CNS0390088/ ,I think).
